implementation of Sing in service, controller, tests and documentation
wolox-training/de-express-js pull request #7
Opened 2020-11-23 22:57 UTC by DEG-W

## Summary

Implementation of Sing in service, controller, tests and documentation

## Known Issues

missing log an test error in case of database failure

## Trello Card

https://trello.com/c/j2f2Nvmm

2020-11-24 01:32 UTC, marioportela1993 requested changes

2020-11-24 01:32 UTC, marioportela1993 commented on app/Utiles/users.js
> +exports.findUserByEmail = (model, email) => model.findOne({ where: { email } });
This function is used in the users service. Maybe you can put this function in the `/services/users.js` file. On the other hand, you can rename the file as token.js o something similar, due to all functions here are used to manage the token.

2020-11-24 01:32 UTC, marioportela1993 commented on app/Utiles/users.js
> +const bcrypt = require('bcryptjs');
Rename the folder as `utils`, don't use `Utiles`,  i.e., change `app/Utiles/` to  `app/utils/`

2020-11-24 01:32 UTC, marioportela1993 commented on app/controllers/users.js
>  const { users } = require('../models');
Call models into services

2020-11-24 01:32 UTC, marioportela1993 commented on app/services/users.js
> +    .catch(error => {
Here you are logged whatever error occurred when you do database operations. 🥇

2020-11-24 01:32 UTC, marioportela1993 commented on app/services/users.js
> +      throw error;
Use a custom error here, you can use the `databaseError` that already exist in the `errors.js` file. Example: `throw databaseError('Database error when trying  to singing in  an user')`

2020-11-24 01:32 UTC, marioportela1993 commented on config/index.js
> +    jwt: {
You can use the `secret` in the `session` key above

2020-11-24 01:32 UTC, marioportela1993 commented on test/controllers/usere.spec.js
> +              .send({ email: user.email, password: user.password })
Change `.send({ email: user.email, password: user.password })` to `.send(user)` is the same. What do you think?

2020-11-24 01:32 UTC, marioportela1993 commented on test/controllers/usere.spec.js
> +          .send({ email: user.email, password: user.password })
Same comment

2020-11-24 01:32 UTC, marioportela1993 commented on test/controllers/usere.spec.js
> +          .send({ email: 'pedro.perez@gmail.com', password: '12345678' })
Change `.send({ email: 'pedro.perez@gmail.com', password: '12345678' })` to `.send({ ...user, password: '12345678' })`, is the same and more beautiful  :)

2020-11-24 01:32 UTC, marioportela1993 commented on test/controllers/usere.spec.js
> +          .send({ email: 'pedro.perez@.wolos.com', password: '123456' })
Same comment

2020-11-24 01:32 UTC, marioportela1993 commented on test/controllers/usere.spec.js
> +      it('Sing in user with no alphanumeric password', () =>
Same comment

2020-11-25 02:53 UTC, DEG-W commented on app/services/users.js
> +    .catch(error => {
I don't know how to identify the database error to separate it from the others

2020-11-25 14:58 UTC, marioportela1993 approved these changes

2020-11-26 03:11 UTC, merged